name: facial-gestalt-xai
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.13
  - torchvision=0.14
  - tensorboard=2.11.2
  - cudatoolkit=11.8
  - pip
  - pip:
    - loguru==0.6.0
    - opencv-python>=4.7.0
    - matplotlib==3.6
    - seaborn==0.12.2
    - pandas==1.5
    - scikit-learn==1.2.0
    - scikit-image==0.19.3
    - captum==0.6.0
    - zennit==0.5.0
    - grad-cam==1.4.6
    - pingouin==0.5.3
    - torchmetrics==0.11.0
    - face_alignment==1.3.5
    - "git+https://github.com/FacePerceiver/facer.git@main"
    - jupyterlab==3.5.2
